README.md
src/Spatie/Browsershot/Browsershot.php

PSR2 + Timeout set support + documentation

Timeout support and documentation

---

src/Spatie/Browsershot/Browsershot.php

Fix width issue when setHeightToRenderWholePage

setHeightToRenderWholePage() width issue

---

src/Spatie/Browsershot/Browsershot.php

Windows support

---

src/Browsershot.php
tests/BrowsershotTest.php

The browser.js option is actually called "margin" not "margins".

Fix "margin" option for PDF creation

---

README.md
src/Browsershot.php
tests/BrowsershotTest.php

This adds ability to specify mobile and touch emulation to puppeteer, thus enabling a more accurate mobile view of any given webpage.

Added mobile and touch functions.

---

CHANGELOG.md
src/Browsershot.php
src/Exceptions/CouldNotTakeBrowsershot.php
tests/BrowsershotTest.php

I've added a failing test for saving to filenames without extensions

Failing test for #131

---

README.md
src/Browsershot.php
tests/BrowsershotTest.php

I've added a new options to make usage of a custom binary/browser script so that custom adjustments can be made without touching the library code.

Add support for custom binary/browser script

---

README.md

Example of how to use `setOption` in order to change the language of a page.
Maybe we could do something more generic about puppeteer's `args` ?

Setting browser locale

---

README.md

Hi, I really like your package and we often use it with Laravel so I thought it would be nice to have a Laravel implementation that made certain tasks easier, such as returning a response with the output file inline or as a download or storing the file as you would with Laravel's own storage drivers. 
Please consider reviewing my implementation and offering it as an alternative to Laravel users.
https://github.com/verumconsilium/laravel-browsershot
Keep up with the awesome job 👍🏻

Add link to laravel driver

---

tests/BrowsershotTest.php

Fix test error caused by PR #180

Fix test error caused by PR #180

---

README.md
bin/browser.js
src/Browsershot.php
tests/BrowsershotTest.php

There's nice waitForFunction on puppteer API
Let's utilize it :)

Add waitForFunction() method

---

src/Browsershot.php

This changes the command generation on Windows systems.

Fix for #189 - no screenshot created on Windows systems

---

README.md
src/Browsershot.php
tests/BrowsershotTest.php

Add method to make setting cookies easier

---

README.md
bin/browser.js
src/Browsershot.php
tests/BrowsershotTest.php

Add type() method to browser.js and Browsershot.php and also include tests for new method and update README.md
Working fix for https://github.com/spatie/browsershot/issues/214

Add type() method to js and php files to allow post requests

---

src/Browsershot.php

added escapeshellcmd() function to the getFullCommand method's return #225

---

bin/browser.js
src/Browsershot.php
tests/BrowsershotTest.php

This PR is to fix the issue #254

Dev cookes bugfix

---

README.md
bin/browser.js
src/Browsershot.php
tests/BrowsershotTest.php

I needed a way to change the value of a form dropdown, I noticed I could update text input fields, and so I modeled the select update on the 'types' functionality. There was already a 'selects' method so I named the function 'dropdown_select'

Add dropdown/select update functionality

---

README.md

Fix the readme with the correct method name
closes https://github.com/spatie/browsershot/issues/285

Rename addChromiumArg() to addChromiumArguments()

---

README.md

Fixes the link to the list of device descriptors.

Update device descriptor list in README

---

README.md
bin/browser.js
src/Browsershot.php
tests/BrowsershotTest.php

Solves https://github.com/spatie/browsershot/issues/312

Add support for HTTP authentication

---

README.md
bin/browser.js

Adds support for Puppeteer's AddScriptTag().
No PHP modified so no test updates included.

Adds support for AddScriptTag()

---

src/Browsershot.php

Added blockDomains() method in Browsershot.php

---

bin/browser.js

With blockDomains() method we can now block a list of domains passed as array.
It uses indexOf() to check if each item in the domains array is present in the URL domain.

Added blockDomains() method to block domains

---

README.md

Added blockDomains() method in README.md

---

bin/browser.js

With blockUrls() method we can now block a list of Urls passed as array.
It uses indexOf() to check if each item in the Urls array is present in the Url.

Added blockUrls() method to block Urls

---

src/Browsershot.php

Added blockUrls() method in Browsershot.php

---

README.md

Added blockUrls() method in README.md

---

README.md

As per https://github.com/puppeteer/puppeteer/commit/5c839f5e48dffd57cbf740f4a980b154682a2d87

Updated dependencies for Ubuntu install

---

README.md
bin/browser.js
src/Browsershot.php
tests/BrowsershotTest.php

feat: add `usePipe` to use pipe instead of WebSocket

---

bin/browser.js

Reverts spatie/browsershot#440

Revert "local file patch"

---

.github/workflows/run-tests.yml
composer.json
tests/BrowsershotTest.php

spatie/image PR: https://github.com/spatie/image/pull/107

Support for PHP 8.0

---

CHANGELOG.md
README.md
src/Browsershot.php
tests/BrowsershotTest.php

This PR adds an option to set the scale of a PDF page.
https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-class-page
**Checklist**

feature: add scale option

---

src/Exceptions/FileDoesNotExistException.php

Added missing back tick to exception message.

Fixed exception message

---

docs/miscellaneous-options/read-redirect-history.md

New page in documentation for redirect history feature (#747)

Redirect History: Update docs

---

src/Browsershot.php

This PR resolves the new issues from #756 and fixes unescaped spaces problem on Windows.
The ```Symfony/process``` library now handles Windows command escaping effectively, while maintaining unchanged the behavior on non-Windows OS.
An example of the error that it fixes is:
```
The command "C:^\Program Files^\nodejs^\node.exe ^"C:^\Users^\Libre-5700X^\Documents^\Projects^\morsy-application^\vendor^\spatie^\browsershot^\src/../bin/browser.cjs^" ^"^{^\^"url^\^":^\^"http:^\/^\/my-domain.local^\/printing^\/labels^\/99afa335-5f1a-4305-ae57-9ff3287fdf2a^\^",^\^"action^\^":^\^"screenshot^\^",^\^"options^\^":^{^\^"type^\^":^\^"png^\^",^\^"path^\^":^\^"C:^\^\Users^\^\Libre-5700X^\^\Documents^\^\Projects^\^\morsy-application^\^\storage^\^\test.png^\^",^\^"args^\^":^[^],^\^"viewport^\^":^{^\^"width^\ …
```

Let Symfony/process handle the command escape on Windows

---

bin/browser.cjs

fixing ?? syntax with ternary for following error
`================ Error Output: ================ sh: 1: npm: Permission denied /var/www/html/dansoe-forsikring/vendor/spatie/browsershot/bin/browser.cjs:382 await page.waitForSelector(request.options.waitForSelector, request.options.waitForSelectorOptions ?? undefined); ^ SyntaxError: Unexpected token '?' at wrapSafe (internal/modules/cjs/loader.js:915:16) at Module._compile (internal/modules/cjs/loader.js:963:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) at internal/main/run_main_module.js:17:47`

fixing ?? syntax with ternary

---

docs/requirements.md

Forge had this error 
```
DEPRECATION WARNING                            
Node.js 14.x is no longer actively supported!
```

Update node version

---

docs/requirements.md

Installation instructions for Ubuntu 24.04

Update Laravel Forge instructions.md

---

docs/miscellaneous-options/performance.md

add disableCaptureURLs() document
