src/Spatie/Browsershot/Browsershot.php
This fixes a bug where phantomjs will not take a screenshot over https.
Details can be found here: http://stackoverflow.com/a/24679134.
=> Added --ssl-protocol=any to phantomjs command

src/Spatie/Browsershot/Browsershot.php
Fixes possible blank screenshots in PhantomJS (e.g. when using SNI)
=> Added ignore SSL errors parameter

src/Spatie/Browsershot/Browsershot.php
Hey @freekmurze, I was having issues with some pages not rendering the `<body>` background. The page http://ianwillia.ms for example came out like so:
The PR implements the fix that [Eivind Uggedal](http://uggedal.com) apparently uses for his site http://mediaqueri.es.
http://uggedal.com/journal/phantomjs-default-background-color/
=> Fixed background color

src/Spatie/Browsershot/Browsershot.php
Hey,
this settings prevents phantomJs from waiting forever. Had this bug once while creating a screenshot.
This setting solved the bug for me!
=> fixed phantomJs timeout setting

README.md, src/Spatie/Browsershot/Browsershot.php
There are possible cases when .png and .jpg not enough. Maybe worth allow more flexible settings for this like here http://phantomjs.org/api/webpage/method/render.html ?
=> Update allowed file extensions

composer.json, src/Spatie/Browsershot/Browsershot.php
This fixes `could not create screenshot` errors for MacOS users without using `setBinPath` and manually downloading phantomjs for Mac.
=> Added binary for mac

README.md, src/Browsershot.php, src/ChromeFinder.php, tests/BrowsershotTest.php, tests/ChromeFinderTest.php
Hey, this PR adds support for rendering arbitrary html input using a new `html` method:
```php
Browsershot::html('<h1>Hello world!!</h1>);
```
This is achieved by creating a temporary html file using the `TemporaryDirectory` component already used in the library, which is then passed to Chrome via `file://` scheme and cleaned up once we have the result.
Use case - a lot of rendered pdfs in web apps like invoices contain private information which makes it awkward to use with Browsershot, since you can't expose this data on a public url. An alternative is to use a temporary file, which can be easily done in a code wrapping Browsershot, but I think it's such a common case it would be nice to have this directly in Browsershot. This makes rendering an invoice as simple as:
```php
$pdf = …
```
=> Add support for html input

src/ChromeFinder.php
For instance, Debian users are most likely to have Chromium than Google Chrome on their system.
=> Add the default path for linux Chromium users

README.md, bin/browser.js, src/Browsershot.php, src/Exceptions/CouldNotTakeBrowsershot.php, tests/BrowsershotTest.php
Follow-up PR for https://github.com/spatie/browsershot/pull/85
- improved error handling when calling the browser
- now correctly returns error instead of waiting for timeout on error
- fixed undefined variable usage & removed unused error handling code
- I don't think we need the `CouldNotTakeBrowsershot` exception at all since Puppeteer should return error if it can't write the screenshot/pdf, but I left it in just to be sure
- updated installation instructions
- based on clean Ubuntu 16.04 installation
We might consider installing Chrome via apt like before, so we can keep it easily updated and avoid installing all these dependencies explicitly - I can PR that later.
=> Puppeteer rework - improved error handling & installation instructions

src/Browsershot.php, tests/BrowsershotTest.php
Puppeteer has a really handy features that allows you to specify paper format instead of sizes.
This makes for more readable and understandable code:
```php
// Paper size
Browsershot::url('https://example.com')->paperSize(297, 210)->save($targetPath);
// Paper format
Browsershot::url('https://example.com')->format('A4')->save($targetPath);
```
Available formats are listed here: https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L780
We can also implement a "enum" class to list available formats instead of manually typing a string. 
Something as easy as:
```php
class PaperFormats
{
const LETTER = 'letter';
const LEGAL = 'legal';
const TABLOID = 'tabloid';
const LEDGER = 'ledger';
const A0 = 'a0';
const A1 = 'a1';
const A2 = 'a2';
const A3 = 'a3';
const A4 = 'a4';
const A5 = …
```
=> Page formats

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
This pull requests adds the possibility to configure the node binary manually by calling the  `setNodeBinary` method.
Furthermore, the default environment in `browser.js` is removed. This fixed environment caused an error to occur when rendering a PDF within a web request. My best guess as to why this happens is because nginx doesn't use the same include paths as the terminal. The result was that PDFs could not be rendered on the fly in a Mac/nginx setup, because `node` was not a known environment.
By making the node binary configurable, this problem can be solved regardless of which system is running the library. A path to the node binary can be specified, and will default to `node`.
=> Configureable node binary

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
This PR adds a configurable option to Browsershot with which you can set a network idle timeout. This parameter is passed directly to Puppeteer, and used to wait x-amount of request idle time before saving the page. This can be useful to wait for asynchronous fonts or images to load.
```
Browsershot::html('Foo')
->setNetworkIdleTimeout(100)
->save($targetPath);
```
=> Add network idle timeout configuration

bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
Hey, this PR adds a `noSandbox()` option, which is needed when running linux in certain virtualization environments.
=> Added "no sandbox" option

src/Browsershot.php
This PR changes the way the `NODE_PATH` is set, so that npm can be run when no specific binary is supplied.
Only when a specific npm binary is supplied will the `NODE_PATH` be set using the custom paths. Otherwise, npm will be executed like normal.
=> Default npm path bugfix

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
Here's another attempt at fixing HTTPS errors that may pop up.
Now you can pass an optional `->ignoreHttpsErrors()`
By default, HTTPS errors are not ignored.
I'm pretty new to this, so I'll add some comments to the PR so you can follow my thought process. Again, no hard feelings if this isn't what you're looking for. I really appreciate the opportunity to contribute, and I'm thankful for all your hard work. I'm open to any and all feedback / suggestions / etc.
Thank you!
=> option to ignore HTTPs errors

README.md, src/Browsershot.php, tests/BrowsershotTest.php
This PR uses the `showBackground` value in the Browsershot class to dictate whether or not Puppeteer's `omitBackground` option should be set when capturing screenshots. 
This could potentially be seen as a breaking change because the `showBackground` value defaults to false, which means that this flag might be set for users without them wanting it to be there. 
I will send a separate PR for the `setOption` idea. 
Thanks!
~Ryan
=> Allow the use of the 'omitBackground' option when capturing screenshots

composer.json
This isn't actually required, is it? 
Right now it's installed always, even on production, which doesn't seem to be needed, or am I overlooking something?
=> Move snapshot assertions to --dev

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
Javascript dialog pop up such as alert, prompt, confirm cause rendering of the site to stop what leads to being unable to take a screenshot. `dismissDialogs()` method automatically close such popups allowing the  screenshot to be taken.
=> Dismiss dialogs feature.

src/Browsershot.php, tests/BrowsershotTest.php
This PR adds a `setOption($key, $value)` method which will allow users to pass options to Puppeteer that are not explicitly covered by the rest of this package.   
Options can be set using dot notation, like so: 
```php
Browsershot::url('https://example.com')
->showBackground()
->landscape()
->setOption('margin.top', '2cm')
->pages('1-3')
->paperSize(210, 148)
->createPdfCommand('screenshot.pdf');
```
=> Add the ability to allow arbitrary options to be passed to puppeteer

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
Based on comments in #124 and #130, this PR adds the ability to set an optional delay on screenshot capture. This is useful when waiting for javascript or lazy-loaded resources to load before capturing. 
The included unit test is basically a best attempt at unit testing that. With potential network issues it's hard to guarantee that is always gonna be correct, without mocking a network request... which we can do if we need to.
=> Add delayed snapshot support

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
Based on puppeteer's emulateMedia option this adds method to set it easily. Especially helpful when generating pdfs, because by default it is set to request 'print' CSS media type of pages.
=> Add a way to set emulated media type page options

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
Added 2 new methods `screenshot()` and `pdf()` to output the screenshot or PDF straight to the browser without having to create a new file.
=> Output image or PDF to browser #140

README.md, src/Browsershot.php
I'd like to propose a new `setNodeModulePath()` method. This allows the specification of an alternate path for the `/node_modules/` directory. 
Here's my use case:
I'm work a screenshot capture tool that works inside of the Drupal CMS: [Web Page Archive](https://www.drupal.org/project/web_page_archive). 
The user can set their node/npm paths directly within the CMS. 
Drupal can really only guarantee write permissions on a few directories within the system. So I copy the package.json file into a separate directory and then runs `npm install` inside of that directory.  Thus the node_modules path gets added to that directory, not the root for `npm_path` which seems to be what Browsershot is currently defaulting to in this situation.
So for example, my code would look something this:
```php …
```
=> Add ability to set node modules path

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
Per the [puppeteer api docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions), we can specify alternate executable path for chrome/chromium: 
>   - `executablePath` <[string]> Path to a Chromium executable to run instead of bundled Chromium. If `executablePath` is a relative path, then it is resolved relative to [current working directory](https://nodejs.org/api/process.html#process_process_cwd).
This PR adds support for this feature.
=> Add puppeteer chrome executable path support

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
Hey, this PR adds a `waitUntilNetworkIdle()` option as a replacement for the old `setNetworkIdleTimeout()` option when using Puppeteer 1.x.
- `waitUntilNetworkIdle()` by default waits for the `networkidle0` event - no network connections for 500 ms
- `waitUntilNetworkIdle($strict = false)` waits for the `networkidle2` event - no more than 2 network connections for 500 ms (useful in edge cases where the website is pinging some ajax endpoint)
I believe this is in most cases better than using the delay option as with delay you are just guessing how long the resource loading will take, so you either waste time waiting or not waiting long enough. With network idle you are only waiting for an extra 500 ms in the best case.
Also I've found this required for webfonts to be properly rendered in …
=> Added "wait until network idle" option

README.md, bin/browser.js, src/Browsershot.php, src/Exceptions/ElementNotFound.php, tests/BrowsershotTest.php
This PR adds a new method `select` which can be used to capture a screenshot of an element matching a selector. It works by finding the [boundingBox](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandleboundingbox) of the element and using it to clip the screenshot.
A coupe things to note:
- If the selector does not match an element, ~~it is ignored~~ an exception is thrown
- it has no effect when creating a pdf, since `clip` is not supported when generating pdf files
=> Add support for taking screenshot of an element using a selector

CHANGELOG.md, README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
Hi,
This PR allows to add HTTP headers to the page call using [extraHTTPHeaders](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetextrahttpheadersheaders) option. Fixes #171
=> Add extraHTTPHeaders options

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
Hi,
This PR adds the [page.click](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageclickselector-options) feature.
Fixes #174
=> Add click feature

.travis.yml, composer.json, src/Browsershot.php, tests/BrowsershotTest.php
The docs suggest that you can set emulateMedia to null to remove emulation, however the emulateMedia method in browsershot is typehinted to a string so this option is not currently possible.  This PR fixes this by removing the typehint.
=> Remove typehint from emulate media

README.md, src/Browsershot.php
Another simpler implementation of Issue #177
=> Add setScreenshotType() method + Update Readme

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
=> Implement evaluate() (squashed commit)

tests/BrowsershotTest.php
the test was there to test the wrong `setBinPath` and the `setChromePath` already existed
=> Fix typo in test where it checked the same thing twice

src/Browsershot.php
This PR just fixes the following deprecation warning:
=> Fix Symfony Process deprecation warning

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
This PR adds the ability to write the options given in Browsershot to a file instead of passing them as command line argument. When passing an options JSON to puppeteer that's too big(e.g. when you have an image as a header) the command line will crash because of a character overflow. We solve this by writing the options to a temporary file and passing the file as an argument instead of the whole JSON dump.
=> Write options to file

README.md, src/Browsershot.php, tests/BrowsershotTest.php
The `paperSize` and `margins` functions are hard coded as `mm`. It would be convenient to allow custom units.
=> Feature custom papersize unit

README.md, src/Browsershot.php, tests/BrowsershotTest.php
Adds the ability to set some custom arguments that will be passed onto Chromium when it is launched.
We required the ability to do this as running Chromium on our CentOS server caused some super bizarre font rendering issues unless we passed on an explicit font hinting flag to Chromium.
Any problems, let me know.
Thanks
👍
=> Allow custom Chromium arguments to be passed on

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
As per #280 this add an option to the package that allows you to disable javascript when capturing pages.
Let me know if you have any issues/suggestions :smile:
=> feat: allow javascript to be disabled

README.md
The Readme stated, that "...custom unit to the `margins` as the fourth parameter."
But the fourth parameter is the `left` margin value. Actually. the `unit` is the fifth parameter.
=> Fixed Readme error for ->margins() method parameter

src/Browsershot.php
Currently, only savePdf() will delete temporary files while generating PDF, pdf() won't.
This commit only add cleanupTemporaryHtmlFile() after PDF has been generated and grabbed in base64.
=> Fix pdf (in-memory) not deleting temporary file on filesystem

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
This PR adds a method to the current API, allowing the configuration of a remote chromium/chrome instance. This instance needs to be running with the following parameter: --remote-debugging-port=<port goes here, default is 9222>
I also modified browser.js to use the connect method of puppeteer. Using the parameter browserURL,  puppeteer will connect with that instance, returning a browser instance, just like using the launch method. If for some reason that instance is not running, browsershot will fallback to launching a chromium instance, continuing is normal flow.
Also i added disconnect methods to browser instance when ending the browser.js script. The page instance is also being closed so the instance is kept clean after running jobs.
I also made some tests, but part of them are …
=> Connect to remote chromium instance

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
I've seen a few HTML to PDF APIs that have this functionality, so I figured I'd try and add it in. 
It uses [an example](https://github.com/puppeteer/puppeteer/blob/master/examples/block-images.js) from Puppeteer's repo to block the actual image requests, and a small loop to go through the DOM and remove all `<img>` elements after the page has been fetched.
=> Adds disableImages method to prevent images from loading

README.md
Puppeteer's DeviceDescriptors.js location has been changed. This PR is to update Puppeteer's DeviceDescriptors.js on README. Thanks!
=> Update Puppeteer's DeviceDescriptors.js location

bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
First of all, thank you very much for this lib. Works like a charm. 
Are you open to introducing the option "browserWSEndpoint" while using `puppeteer.connect`. I'm using https://www.browserless.io/ and that works by settings the `browserWSEndpoint` value like:
```
const browser = await puppeteer.connect({
browserWSEndpoint: 'wss://chrome.browserless.io/'
});
```
They don't have an way to work with the `browserURL` option so hench the PR.
As far as the unit test I wrote. I don't know if you would like it to be enable by default? It depends on this external service to be online. We can either comment it out like the "remoteInstance" tests or keep it like this. Your call.
I do have added a test / assets to check of the WS Endpoint is online by just doing a `assetsContains` on the url …
=> Add use of WS Endpoint option

README.md
Browsershot seems to be working great with puppeteer 3.0. I only had to install the `ibgbm-dev` dependency after upgrading from 2.0 to 3.0. Updated the readme to reflect the need of that new dependency.
=> Libgbm-dev dependency for puppeteer 3.0

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
Each request made to a website can trigger more requests, like loading the CSS files & everything. You are able to block certain ones, but you can't get a list of them.
This PR adds a new `triggeredRequests()` function that outputs a JSON string with all of the loaded URLs.
~~It can later be transformed into an array as stated in the readme.~~
Apart from `url`, I don't know what other data might be needed and that can be added to the list.
=> [feature] Get the list of triggered requests

bin/browser.js
Puppeteer v5.0.0 has removed the top-level file `puppeteer/DeviceDescriptors` from the Puppeteer package ([#6043](https://github.com/puppeteer/puppeteer/pull/6043)), causing the following error when using the `->device()` option:
`Error: Cannot find module 'puppeteer/DeviceDescriptors'`
The same data is exposed via `puppeteer.devices`, so `bin/browser.js` should be updated accordingly.
=> Account for the removal of require('puppeteer/DeviceDescriptors')

bin/browser.js
The emulateMedia method was removed in https://github.com/puppeteer/puppeteer/pull/6084 (version 5.0)
emulateMedia was an alias of emulateMediaType
=> Replace emulateMedia call with emulateMediaType

bin/browser.js
This PR modifies `bin/browser.js` to export `callChrome()` and enable passing in a puppeteer instance.
This allows you, when using `setBinPath()`, to create your own minimal script which configures a puppeteer instance and then calls the standard `callChrome()` with it to use the rest of Browsershot's default implementation.
**Why?**
To make it easier to use Browsershot with tools like [puppeteer-extra](https://www.npmjs.com/package/puppeteer-extra) without having to completely write your own implementation of `bin/browser.js`.
Here's an example from one of my projects:
`src/example_php.php`
```php
//...
$bs = Browsershot::url("index.html");
$bs -> addChromiumArguments(["no-sandbox"]);
$bs -> setBinPath(dirname(__DIR__) . "/libs/browsershot.js");
//...
```
`libs/browsershot.js` …
=> `browser.js` export `callChrome()`

bin/browser.js
This library  is creating temporary files and loading them up with file:/// protocol scheme [https://github.com/spatie/browsershot/blob/4148f910735cf385070cb1a6ff1ac26a37eefd10/src/Browsershot.php#L707](url) when 'Browsershot::html' function is used. Using a file protocol scheme along with headless browser such as Chrome on a server side is not a good idea and will lead to Local file disclosure (Security Vulnerability). Other local files present on the server could be loaded when a malicious HTML is provided. Local files can be loaded either with <iframe> (e.g. <iframe src="file:///etc/passwd" width= height=>) or by setting the different document location. Also, it is unlikely for the developers to check each and every page for malicious JavaScript inputs. This vulnerability can be …
=> local file patch

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
This PR modifies `bin/browser.js` to to allow passing arbitrary environment variables to the browser instance when launching.
Users can now use `setOption('env', ['TZ' => 'FOO'])` to set specific environment variables which are visible to the browser.
**Why**
For our specific use case we wanted to set the timezone of the browser to match the user, I'm sure there will be other use-cases for this functionality beyond timezones.
**Tests** 
Appears it's not currently possible to test `browser.js` in this manner, but a test has been added for the php implementation of `setEnvironmentOptions`.
**API Changes**
A new method was added to the Browsershot class 
```php
$instance->setEnvironmentOptions([
'FOO' => 'BAR',
]);
```
=> Adding ability to pass envars to browser instance

bin/browser.js
Hi!
When using the delay, the following error will be logged:
```
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
```
Seems like waitFor on the page object was deprecated based on this issue https://github.com/puppeteer/puppeteer/issues/6214.
I replaced it following the recommendation in this comment: https://github.com/puppeteer/puppeteer/issues/6214#issuecomment-717895793
Hope this helps 🤘
=> Replace waitFor with waitForTimeout as its deprecated

bin/browser.js
I am using an approach similar to https://github.com/spatie/browsershot/pull/399#issuecomment-700730688 to run Browsershot on Vapor.
While `callChrome()` being exposed helps out a lot already, it still depends on the `puppeteer` library being installed.
Since `chrome-aws-lambda` uses `puppeteer-core`, browser.js crashes when being executed, even if you pass a custom instance.
This PR moves the actual require call into the function, so it will only be loaded when necessary.
There was also one extra line where the wrong instance was being used.
=> Use local require for puppeteer

README.md, bin/browser.js, src/Browsershot.php
I would like to get the screenshot of the nth element on a page but `document.querySelector` cannot handle `eq:(xx)` like
document.querySelector('body:eq(0)')
The solution would be to use 
document.querySelectorAll('body')[0]
=> Introduce a selectorIndex to bypass querySelector restrictions.

composer.json
We cannot use Mailcoach together with this package because Mailcoach requires 2.0.
Just like https://github.com/spatie/laravel-sitemap/pull/379 ;)
=> Bump temporary-directory to version 2.0

README.md, src/Browsershot.php, tests/BrowsershotTest.php
This package is platform agnostic, as such, functionality provided by the Laravel framework such as file uploads becomes a tricky issue on environments like Heroku where files can't be created on its ephemeral storage. Therefore, to use this in such an environment proves almost impossible. 
This PR introduces a `base64pdf()` method. This method allows for a PDF to be created and returned as a base64 string, just like the `base64Screenshot` method. With the base64string, you can be able to use that to create a file using the laravel Storage facade which will persist it to your disk of choice keeping it in memory. Alternatively, using the Spatie Laravel Media Library, you can directly upload the base64 string to your disk of choice. 
```php
$base64_pdf = …
```
=> Add base64pdf method

README.md
Hi,
I think it's time to update the installation instructions for forge servers to use latest chrome and node versions. Especially `libxshmfence-dev` is now needed to make chrome work properly.
Home this helps ✌️
=> Update and fix install instructions for Forge servers

README.md, src/Browsershot.php, tests/BrowsershotTest.php
There are multiple ways to skin this cat, as it is a direct option for the puppeteer [launch options](https://pptr.dev/#?product=Puppeteer&version=v10.2.0&show=api-puppeteerlaunchoptions) as `userDataDir`, but could also just be set with the `args` option. I chose using the `args` option as it seemed less invasive. This theoretically should fix #101.
=> Add support for the `--user-data-dir` flag

README.md, bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
When opening pages the extra headers are sent with all subsequent request. Not every domain plays well with this strategy.
Domains with `Access-Control-Allow-Headers` will fail in preflight checks. 
I've added the option to set headers which are only send with navigational requests (e.g. the main request).
(i also converted inconsistent indenting in the browser.js file to spaces)
=> Added functionality to only send headers with navigational requests.

bin/browser.js, src/Browsershot.php, tests/BrowsershotTest.php
I found 3 issues with these methods:
- `Browsershot.php` was encoding the blocked URLs and domains twice: using `json_encode()` within the method itself and then a second time inside `getFullCommand()`. Which would generate this JSON:
```json
"blockDomains":"[\google-analytics.com\,\fonts.googleapis.com\]"
```
and cause this error:
```
SyntaxError: Unexpected token g in JSON at position 418 at JSON.parse
(Invalid escape character in string)
```
instead of generating this JSON:
```json
"blockDomains": ["google-analytics.com", "fonts.googleapis.com"]
```
- `browser.js` was referring to a variable named `domainsArray` which did not exist anymore
- `browser.js` was trying the parse the hostname from the `request` variable instead of the `interceptedRequest` variable
I added some missing tests …
=> Fix blockDomains and blockUrls methods

src/Browsershot.php
If you are running Browsershot on Apple Silicon, you will run into issues with your path. This PR adds the new Homebrew directory to the default path and fixes https://github.com/spatie/browsershot/discussions/580.
=> Fix Apple Silicon Path Issue

composer.json
As mentioned in #588 it seems to work well also with `symfony/process` in version `6.0` and analogue to the proposed change in `spatie/image`.
=> Adding compatibility to Symfony 6

docs/introduction.md
Update the puppeteer GitHub link, because the old link redirected to new GitHub repo of puppeteer
=> Update Puppeteer GitHub link

src/Browsershot.php
Currently function arguments are not being used with `mobile()` and `touch()` function.
This change makes it possible to explicitly set options to `false` by using the function arguments.
=> Use function arguments for `mobile` and `touch`

.github/workflows/run-tests.yml, composer.json, tests/BrowsershotTest.php, tests/Pest.php
This pull request contains changes for migrating your test suite from PHPUnit to [Pest](https://pestphp.com/) automated by the [Pest Converter](https://laravelshift.com/phpunit-to-pest-converter).
**Before merging**, you need to:
- Checkout the `shift-57949` branch
- Review **all** of the comments below for additional changes
- Run `composer update` to install Pest with your dependencies
- Run `vendor/bin/pest` to verify the conversion
=> PHPUnit to Pest Converter

src/Browsershot.php
The call to `CouldNotTakeBrowsershot::chromeOutputEmpty()` now requires a second argument, since 50eae92
=> Update savePdf to comply with 50eae92

bin/browser.js
Fixes this error that happens when using blockUrls() with NodeJs v17.8.0:
```
Exit Code: 1(General error)
Working directory: /root/browsershot
Output:
================
Error Output:
================
/root/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
throw new Error(message);
^
Error: Request is already handled!
at assert (/root/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
at HTTPRequest.continue (/root/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPRequest.js:304:32)
at /root/browsershot/vendor/spatie/browsershot/bin/browser.js:143:40
at /root/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:219:52
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async HTTPRequest.finalizeInterceptions …
```
=> Fixed issue Error: Request is already handled! in NodeJs v17.8.0

docs/usage/creating-pdfs.md, src/Browsershot.php, tests/BrowsershotTest.php
See #628 for background
Let me know if this is okay or if you require anything more!
=> Add support for `omitBackground`

bin/browser.js, docs/miscellaneous-options/using-url-for-html-content.md, src/Browsershot.php, tests/BrowsershotTest.php
This pull request adds a new method called setContentUrl.
When using the method html, sometimes you may have relative paths in your code, that needs a base url to be completely fetched. This feature allows setting this url into puppeteer.
=> Added method setContentUrl to set url when using html method

src/Browsershot.php
If you are running browsershot on Windows, the writeOptionToFile wasn't used for the command
=> Enable writeOptionsToFile for Windows

bin/browser.js, tests/BrowsershotTest.php
When submitting a post request through Browsershot you get the following error:
```
Error: Request is already handled!
at assert (browsershot/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:28:15)
at HTTPRequest.continue (browsershot/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPRequest.js:349:32)
at browsershot/bin/browser.js:198:40
at browsershot/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:275:32
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async HTTPRequest.finalizeInterceptions (browsershot/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPRequest.js:188:9)
```
This is caused by intercepting the request twice in the browser.js script.
I've added a test that performs a real post which fails on the existing code and works …
=> Prevent double request interception on POST

README.md, src/Browsershot.php, src/Exceptions/FileDoesNotExistException.php, tests/BrowsershotTest.php
Sometimes it is necessary to have all the html contents in a local file rather than on a url or in a PHP string due to memory limits. The introduced function `htmlFromFilePath` makes it clear you are intending to set the html from a local file, and there for if the input is not being generated by the user themselves, they should validate the file path is allowed before allowing it to be used.
With 92cf16fc098211731f80d21687abeafbe2c457ad I assume this functionality was removed out of safety concerns.  However, for multiple projects we need to generate the PDF from HTML that is stored in a file that we incrementally build as some of HTML can larger than we want to store in memory. By having the explicit `htmlFromFilePath` it should be clear that a local file is going to be included, so the …
=> Allow user to explicitly use a local file for html content.

.github/workflows/run-tests.yml
This PR adds PHP 8.2 support to the GitHub tests workflow, as well as upgrades the `actions/checkout` action to latest version (v3).
=> Add PHP 8.2 Tests Support

docs/miscellaneous-options/changing-the-language-of-the-browser.md
It seems that a recent Chromium update broke setting the language through `setOption()` with `args`. 
(A user of mine mentioned that their custom language setting was no longer working as expected).
Apparently the proper way to set the language of the browser is to use a `LANG`-environment variable.
- https://bugs.chromium.org/p/chromium/issues/detail?id=755338#c14
- https://github.com/puppeteer/puppeteer/issues/1871#issuecomment-365012490
- https://github.com/puppeteer/puppeteer/issues/5970#issuecomment-690677674
=> Docs: Use setEnvironmentOptions to set Browser Language

docs/usage/creating-images.md
Link to Puppeteer devices list is broken. Puppeteer repo structure has changes and removed Devices description that was previously linked. Updated link.
=> Fix link to Puppeteer devices in creating-images.md

bin/browser.cjs, src/Browsershot.php, tests/BrowsershotTest.php
Sometimes it can happen that the screenshot made by Browsershot is different from the one displayed by your browser.
It is often due to one or more redirects made by the site, based on geolocation, cookies, etc...
To understand what happens, I tried to keep track of the redirects made by the site, both HTTP, Javascript and HTML ones, not using only the Puppeteer redirectChain because it only considers the HTTP ones.
I tried to capture any request that is a navigation requests that attempts to load a new document, mke sure the redirect is in the parent frame or we will see the navigation for other frames.
Since they are available, in addition to the URLs I thought of including HTTP status, reason and headers.
=> Read redirect history

src/Browsershot.php
I'm encountering a similar escaping issue on Windows as described in #681.
However, in the current version, the Windows command appears to be completely broken.
This PR addresses the problem and fixes the execution on Windows.
=> Fix Windows command escaping

src/Browsershot.php, tests/BrowsershotTest.php
Hi,
when using `Browsershot::html()` in combination with the following methods, `bodyHtml()`, `base64Screenshot()`, `screenshot()`, `base64pdf()`, `evaluate()`, `triggeredRequests()`, `consoleMessages()` or `failedRequests()`, the temporary html files never get deleted. Similar methods like `pdf()` already clean up tmp html files.
There's also a minor fix for the "can get the failed requests" test.
=> Cleanup temporary html files

docs/requirements.md
The latest versions of Puppeteer do not play nicely on Forge. Constraining to v17 works however. #681 refers
=> Update requirements.md for Forge provisioning

bin/browser.cjs, docs/usage/creating-images.md, src/Browsershot.php, tests/BrowsershotTest.php
This PR adds waitForSelector()
This puppeteer functions allows to wait for a selector to be visible in the page before printing.
This has two main use cases.
1- Wait for some content to be loaded via ajax, when that content is loaded a selector will be visible. Only then print the page
2- This can be used as an improvement to the performance.
Instead for waiting for networkidle0 or networkidle2, we can wait for a selector, once that selector is visible the print will start.
This way we don't need to wait for the connections to be closed when using networkidle0 or networkidle2
This function accepts two parameters
1- Selector which is required
2- WaitForSelectorOptions which is optional (For more info please check link below)
Puppeteer docs page for waitForSelector(): …
=> Add waitForSelector()

docs/usage/creating-pdfs.md, src/Browsershot.php, tests/BrowsershotTest.php
Adding a `taggedPdf()` method as discussed in discussion #799
=> Adding a taggedPdf option

src/Browsershot.php
Currently, this property is defined as a nullable string. Puppeteer throws an exception when setting screenshot quality.
> Error: Expected options.quality to be a number but found string at assert (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15) at CDPPage.screenshot (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:777:36)
=> [Fix] Change `screenshotQuality` property type to integer

bin/browser.cjs
The `page.waitForTimeout` method in Puppeteer was removed in v22. Therefore, using the `setDelay` method on a Browsershot instance will result in the following error:
```
TypeError: page.waitForTimeout is not a function
at callChrome (.../vendor/spatie/browsershot/bin/browser.cjs:331:24)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
As recommended in the [documentation for older versions of Puppeteer](https://github.com/puppeteer/puppeteer/blob/puppeteer-v21.11.0/docs/api/puppeteer.page.waitfortimeout.md), replace `page.waitForTimeout` in `browser.cjs` with `await new Promise(r => setTimeout(r, request.options.delay))`.
=> Replace waitForTimeout

tests/BrowsershotTest.php
When testing the redirect history on http://www.spatie.be, the test expected 3 redirects:
1. http://www.spatie.be -> http://www.spatie.be/ (trailing "/")
2. http://www.spatie.be/ -> https://www.spatie.be/ (https)
3. https://www.spatie.be/ -> https://spatie.be/ (remove "www")
However, the first two now happen in one redirect, i.e.:
1. http://www.spatie.be -> https://www.spatie.be/ (https + trailing "/")
2. https://www.spatie.be/ -> https://spatie.be/ (remove "www")
Therefore, I altered the test to expect only two redirects instead of three.
I assume that the test failed due to a change on the spatie.be domain.
=> Fix redirect history test

docs/requirements.md
I just went through the Browsershot installation process and ran into a few issues. After reading [discussion #681](https://github.com/spatie/browsershot/discussions/681) I found a pretty simple solution that uses the latest versions of nodejs and Puppeteer without locking to an [outdated version 17 of Puppeteer](https://github.com/puppeteer/puppeteer/releases/tag/v17.1.3).
The critical command seems to be
```bash
npx puppeteer browsers install chrome
```
Which I found from the following error output from Puppeteer:
```
================ Error Output: ================
Error: Could not find Chrome (ver. 123.0.6312.122). This can occur if either 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or 2. your cache path is incorrectly …
```
=> Update installation instructions for nodejs + Puppeteer

composer.json
Having installed latest `spatie/image` version, we'll avoid dependant bot alerts.
=> Fixing `spatie/image`'s dependant bot alerts issues in `composer.lock`

src/Browsershot.php
After the change on this commit https://github.com/spatie/browsershot/commit/bf0307c592c981e9a725e8a62f9775fb64dfbcd3#diff-a4f3311910f99a1fe69b5fab2bcdb806288e552fe7ad5610ddb90f6a331aca37 the save method requires the spatie/image dependency even if you don't have any image manipulations.
Previously you could save an image without the need of the image dependency.
This test couldn't catch the issue because the dependency is not missing.
```
it('can take a high density screenshot', function () {
$targetPath = __DIR__.'/temp/testScreenshot.png';
Browsershot::url('https://example.com')
->deviceScaleFactor(2)
->save($targetPath);
expect($targetPath)->toBeFile();
});
```
=> Fix save method if there are no image manipulations

src/Browsershot.php
[This request](https://spatie.be/docs/browsershot/miscellaneous-options/getting-failed-requests) currently takes 2 screenshots instead of 1 if there are no failed requests recorded:
```php
Browsershot::url('https://example.com')->failedRequests()
```
That's because `if ([/* empty array */])` returns false so Browsershot thinks the output hasn't been generated yet.
Checking for a non null value fixes this issue.
=> Prevent taking screenshots twice

src/Browsershot.php
When using the option `->writeOptionsToFile()` when the PDF is successfully generated the temporary files are not removed causing the temp file to build over time eventually running out of disk space.
When saving a PDF which internally calls the `callBrowser()` function, after retrieving the chromium result run the `$this->cleanupTemporaryOptionsFile()`.
=> Fix - Clean up the temporary options file when browser was called successfully

bin/browser.cjs, src/Browsershot.php, tests/BrowsershotTest.php
Hi
This feature helps to reduce memory when using [data urls](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs).
```php
Browsershot
::HTML('More data urls exists in this document'')
->disableCaptureURLs()
;
```
=> option to disable the capturing request

bin/browser.cjs, src/Browsershot.php
When generating large PDF, getting error:
> ProtocolError: Page.printToPDF timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
This PR can specify `protocolTimeout()` on Browsershot. Example usage:
```php
$browsershot->protocolTimeout(60); // 60 seconds
``` 
By default the value of `protocolTimeout` is 30 seconds.
=> Add options to set protocol timeout

bin/browser.cjs
This PR addresses a bug(?) introduced in [#861](https://github.com/spatie/browsershot/pull/861).
The option appears to be reacted to incorrectly. Perhaps the semantics should be inverted as well, i.e. change the option to "enableCaptureURLS" and enable it by default?
=> Correctly respond to disableCaptureURLS option

bin/browser.cjs, src/Browsershot.php
Puppeteer modified how they return stream data, for browser compatibility reasons ([#12823](https://github.com/puppeteer/puppeteer/issues/12823))
After this update, a UInt8Array byte stream is returned, instead of a Buffer.
This PR adjusts the handling of this output to be compatible with v23's output. All tests appear green, save for three which fail due to the requests list not being populated. I believe I know the cause, and will submit a PR to fix it.
Tests remain green when running Puppeteer 22.15.0 as well, so this fix should be backwards compatible with older versions that returned a Buffer rather than UInt8Array.
=> Update handling of browser output for Puppeteer ^23.0.0

.github/workflows/run-tests.yml, README.md, bin/browser.cjs, composer.json, src/Browsershot.php, tests/BrowsershotTest.php, tests/PdfTest.php
This pull request reintroduces the changes done for Puppeteer v23, while fixing the issue introduced in https://github.com/spatie/browsershot/pull/870 resulting in a white PDF.
The issue was caused by not using base64 to communicate between puppeteer and Browsershot.
I also added a test that actually checks the contents of the PDF. To do this, I introduced the pdf-to-text package used in https://github.com/spatie/laravel-pdf and also added the same note in the README.
There is still one flaky test: 'can handle a permissions error with full output', which expects no errors, but sometimes gets a 404 on the favicon of example.com (because they have not favicon). It doesn't always fail, because the request for a favicon happens asynchronously.
=> Fix empty PDF issue with Puppeteer ^23.0.0 

CHANGELOG.md, bin/browser.cjs, docs/miscellaneous-options/disabling-redirects.md, src/Browsershot.php, src/Exceptions/FileUrlNotAllowed.php, src/Exceptions/HtmlIsNotAllowedToContainFile.php, tests/BrowsershotTest.php
1. There are currently checks in `src/Browsershot.php` to ensure that external linking to a file does not work, as this very easily introduces a security vulnerability. 
In this PR - I simply introduce a further check to not only check for `file://` but also for `file:/` - which also works for linking to local files alongside some tests to check this.
A straightforward POC to demonstrate this being used is:
`Browsershot::url('file:/etc/password')->save("vuln.pdf");`
Which allows the password file to be generated out as a PDF. This flaw can be further exploited to bypass the security filters and read local files from the applicationserver through the use of iFrames, leading to unauthorised access and potential data compromise.
2. There exists the ability to _not_ follow redirects in …
=> Added file:/ to the list of excluded paths and string contains & added option to disable redirects

bin/browser.cjs, src/Browsershot.php, tests/BrowsershotTest.php
With the release of [Puppeteer v23](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v23.0.0) the `ignoreHttpsErrors` was renamed to [`acceptInsecureCerts`](https://pptr.dev/api/puppeteer.browserconnectoptions/#acceptinsecurecerts).
Updated the `ignoreHttpsErrors()` method to use the new `acceptInsecureCerts` option.
=> Fixed `ignoreHttpsErrors()` method

bin/browser.cjs
https://github.com/spatie/browsershot/blob/02d17646ce0db9eafe923c6149de4da97808232a/bin/browser.cjs#L95
In current Puppeteer versions (v22+ according to the docs), `{headless: true}` actually launches the new headless mode, while `{headless: 'shell'}` launches the old mode:
- https://pptr.dev/guides/headless-modes
This makes it currently impossible to use the old headless mode with Browsershot, which is our preferred mode for creating PDFs, and the only mode that, in our experience, actually works with Basic Auth.
See https://developer.chrome.com/blog/chrome-headless-shell for more details.
---
Note: We were previously able to work around this issue by enabling the old headless mode the following way instead:
```php
$browsershot->addChromiumArguments([
'headless' => 'old', // see …
```
=> support `chrome-headless-shell` (old headless mode)

.github/workflows/run-tests.yml
Should fix the `No usable sandbox!` error as seen in https://github.com/spatie/browsershot/actions/runs/13367517414, via https://github.com/puppeteer/puppeteer/pull/13196. Tests still fail with this, but for different reasons.
=> run-tests: disable app armor restrictions

bin/browser.cjs
Browsershot includes the ability to clip the exported image to a specific element using a `selector` option, as well as a `waitForSelector` option to wait until a certain selector appears on the page. It seems pretty useful to use these options together, eg:
```php
$browsershot
->waitForSelector('.export-target') // Wait until ".export-target" element appears on the page.
->selector('.export-target') // Only include that element in the screenshot
->save();
```
This is currently *not* possible, as the puppeteer script processes the `selector` option *before* `waitForSelector`.
This PR simply changes the order of how the options are processed, so the `selector` option is processed *after* `waitForSelector` and `waitForFunction`.
=> Apply selector after wait for selector/function instead of before

bin/browser.cjs
This PR adds a check that `frame()` exists before checking `parentFrame()`. 
Currently the code is `response.request().frame().parentFrame()` which will throw a `TypeError: Cannot read properties of null (reading 'parentFrame')` when `frame()` is null. 
Issue raised here: https://github.com/spatie/browsershot/discussions/895
Puppeteer docs confirming `frame()` can be null: https://pptr.dev/api/puppeteer.httprequest.frame
=> Fix | Check that response().frame() is not null

bin/browser.cjs, tests/BrowsershotTest.php
Some pages may throw `null` as error. This leads to TypeError when collecting the page errors information. Set "null" as the message in such cases as there is no other meaningful value.
=> Fix handling of page errors with value `null`
